apiVersion: apps/v1
kind: Deployment
metadata: 
  name: meudeployment
spec:
  replicas: 8
  selector:
    matchLabels: 
      app: exemplo
  template:
    metadata:
      labels:
        app: exemplo
    spec:
      containers:
        - name: meucontainer
          image: nginx

