apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meureplicaset  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata: 
      labels:
        app: nginx
    spec:
      containers:
        - name: meucontainer
          image: nginx 
